# site settings
title: Portafolio ER
subtitle: Emanuel Reyes
email: office.earc@gmail.com
description: El portafolio audiovisual de Emanuel Reyes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emanuelreyesc.github.io/" # the base hostname & protocol for your site
author: Emanuel Reyes
phone: +569 30327002

# social settings
500px_url:
facebook_url:
github_url: https://github.com/andrewbanchich
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/emanuel-reyes-castro-204160225/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich
whatsapp_url: "https://wa.me/+56930327002"

# build settings
markdown: kramdown

sass:
  style: compressed
